### ISSUE TITLE
LineSegment should have equals

### ISSUE THREAD

**Issue by idontusenumbers** [lessthanoptimal/GeoRegression#12]
LineSegment2D_F32 uses the default Object equals implementation, using identity and hashcode making it impossible to compare equality of two line segments that aren't the same element.

**Comment by lessthanoptimal** [comment]
Do you want to see if two line segments are perfectly identical or equivalent to numerical precision? equals() implies perfectly identical which isn't a good idea in general for floating point numbers.

**Comment by idontusenumbers** [comment]
exactly the same bit-for-bit would satisfy my need, a function with variable precision would be cool too.

**Comment by lessthanoptimal** [comment]
done. You can get it in the latest SNAPSHOT. A new stable should be out in the not too distant future.
