### ISSUE TITLE
Point2D_I32 (and likely others) do not behave as expected in Java Set

### ISSUE THREAD

**Issue by nicost** [lessthanoptimal/GeoRegression#13]
Example in beanshell:

`p1 = new Point2D_I32(37, 39);`
`p2 = new Point2D_I32(37, 39);`
`s = new HashSet();`
`s.add(p1);`
`s.add(p2);`
`mm.scripter().message("Point2D_I32 Set size: " +  s.size());`
Point2D_I32 Set size: 2

whereas:
`pp1 = new Point(37, 39);`
`pp2 = new Point(37, 39);`
`ss = new HashSet();`
`ss.add(pp1);`
`ss.add(pp2);`
`mm.scripter().message("Point Set size: " + ss.size());`
Point Set size: 1

I believe this is caused by Point2D_I32 (and friends) defining the equals method, but not hashCode, hence Java does not see two instances of Point2D_I32 with the same values as being equal.  I am working around this by converting everything to Point (guess it is more elegant to inherit from Point2D_I32 and define hashCode myself), but this behavior is a bit unexpected.

**Comment by lessthanoptimal** [comment]
Haven't used points like this. Used IntelliJ to autogenerate hash code. Pushed into SNAPSHOT.

**Comment by nicost** [comment]
Yes!  That fixes it!  Thanks!
