### ISSUE TITLE
Tutorial Needed.

### ISSUE THREAD

**Issue by changbaishan** [lessthanoptimal/GeoRegression#14]
Hi Peter,

I want to get my hands on GeoRegression but don't know where to start. Can you please find time writing a tutorial?

Thanks very much.

**Comment by lessthanoptimal** [comment]
Did you look at the examples? Is there a specific problem you're interested in?

**Comment by changbaishan** [comment]
I looked the examples. But I did not have the mental click. At the moment, I am interested in projections. 

I hope you write an introduction: How geoprojection meant to be used. How to approach from higher level. Your tutorials on boofcv is full of sparks. You certainly got that, just need to share so your user community can click with you.

**Comment by Developer66** [comment]
Hey,
is it possible to fit a line to a 3D Point cloud with this libary?

Thanks

**Comment by lessthanoptimal** [comment]
A bit surprising but that doesn't seem to exist yet. I'll add it to the list of new features that I hope to add, but if you feel inspired and want to add it let me know!
