### ISSUE TITLE
Typo in description of the UtilAngle.wrapZeroToOne

### ISSUE THREAD

**Issue by xzvfinet** [lessthanoptimal/GeoRegression#6]
It's minor typo. The result of **UtilAngle.wrapZeroToOne(2.0f)** is **0.0f** not 1.0f.

[UtilAngle.java](https://github.com/lessthanoptimal/GeoRegression/blob/master/main/src/georegression/metric/UtilAngle.java) - Line 379, 401

**Comment by lessthanoptimal** [comment]
fixed.  Thanks!
