### ISSUE TITLE
GeoRegression 0.13 incompatible with EJML 0.32

### ISSUE THREAD

**Issue by ennerf** [lessthanoptimal/GeoRegression#7]
EJML changed **LinearSolver\<DMatrixRMaj\>** to **LinearSolverDense\<DMatrixRMaj\>** or **LinearSolver\<DMatrixRMaj, DMatrixRMaj\>**

GeoRegression still uses the older format in the following files:

* FitEllipseAlgebraic_F32
* FitEllipseAlgebraic_F64
* FitEllipseWeightedAlgebraic_F32
* FitEllipseWeightedAlgebraic_F64
* MotionAffinePoint2D_F32
* MotionAffinePoint2D_F64

Best,
Florian

**Comment by lessthanoptimal** [comment]
Released 0.14 which should fix those issues.
